<?php

namespace AppBundle\Repository;

/**
 * EmployeeLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
