<?php

namespace AppBundle\Repository;

/**
 * EmployeeSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
